# Generated by Django 4.1.1 on 2022-10-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='point',
            new_name='score',
        ),
    ]
