# Generated by Django 4.1.1 on 2022-10-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(default='', max_length=555),
        ),
    ]
