# Generated by Django 4.1.1 on 2022-10-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_image',
            field=models.ImageField(default='shorturl.at/djq69', max_length=255, null=True, upload_to='images/'),
        ),
    ]
