# Generated by Django 4.1.1 on 2022-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_image',
            field=models.ImageField(default='/images/default-image2.jpg', max_length=355, null=True, upload_to='images/'),
        ),
    ]
